### ISSUE TITLE
No functions in Threads.js

### ISSUE THREAD

**Issue by u13073878** [BuzzSpaceB/Threads#4]
Hey guys. The module does not provide functions to allow mid-level integrators to interface with Threads and Contents. We cannot access the constructors. Please create functions in a form similar to:

module.exports.createThread = function(...){ ... }

that will allow us to interface with the module.
Thanks.

**Comment by thepickpocket** [comment]
This has been resolved, please have a look at our experimental branch where I am currently working at resolving some of the major glitches and errors.

**Comment by u13073878** [comment]
OK cool. Thanks. :)
